### ISSUE TITLE
Problem with Emoji.replaceInText(myString)

### ISSUE THREAD

**Issue by saket** [delight-im/Emoji#1]
Hello, thank you for your Emoji class! You just saved me a couple of hours, but it seems to work even when the smileys are a part of words. 

For instance, the "xD" in this text: "xDA" will also get replaced by its equivalent smiley which shouldn't happen. 

These are the cases the algorithm must consider:
1. Space before and after the smiley
2. Space before the smiley and there's no more text after it
3. Smiley is at the starting and space after it
4. Smiley is the only text (after trimming spaces)

I'm terrible with Regex so I have no idea how to improve it. Any suggestions?

**Comment by ocram** [comment]
Thank you very much for reporting this!

As you can see [here](https://github.com/delight-im/Emoji/blob/090aac32ff00d9a592f4098c3ceb7ca8b6399450/Java/Emoji.java#L31), there is a list of excluded characters that may not precede or follow the emoticon. These characters are `-_)(;:*<>=/`.

This prevents the library from finding the emoticon `:/` in `http://` for example.

Now to prevent the bug that you reported, we could just add `a-zA-Z0-9` to that list, right?

This would prevent the library from finding `xD` in `xDA` because it is followed by an `A`.

It would also prevent the library from finding `:3` in `08:30` because it is followed by a `0`.

Do you think that would help?

**Comment by saket** [comment]
Wow that was so simple! Yes that should solve the problem. I have one more question if you don't mind. Since I couldn't find any help that day, I decided to use this inefficient line:

```
text = text.replace(
    " " + emoticon + " ",
    " " + unicodeChar + " "
);
```

And it's working nicely. I haven't seen any issues yet. Plus I also found `replace()` be faster than using `replaceAll()` with a regex pattern. Is there still any other reason I should not go with my method?

**Comment by ocram** [comment]
Fixed in https://github.com/delight-im/Emoji/commit/d819438e3ea9c8aa16339d09d08ccc85ebd45974

Your code is faster, of course, and much more simple, but it does not match emoticons in the following situations:
- at the beginning of a string
- at the end of a string
- after a line break
- after a non-Latin character, as in `κόσμος:)`

Regarding the performance: Did you actually measure the difference? It's probably not so significant that you can observe it.

**Comment by saket** [comment]
Yes I did and something weird happened. Your code, which was taking around 30-50ms for replacing emojis in a few lines of text on my laptop only consumes 0-1ms of time on my phone. Is this normal lol?

I was handling smileys at the beginning and at the end by manually finding them using `startsWith()` and `endsWith()`, but you're right, it doesn't cover the other 2 cases.

Thank you for the new fix. Knowing very little about Regex is something I have always felt bad about. :/

**Comment by saket** [comment]
Update: Nope, it was my code that takes 0-1 ms top even for messages with several lines. I'm using your code in a list and the overhead is too high. It's taking 10ms on average, even for text pieces consisting of 1-2 lines. 

Here's my code:

```
public static String replaceInText(String text) {
    if(text == null) return null;

    String emoticon;
    String emoticonWithSpaces;
    Integer codepoint;
    final int textLengthWithoutSpaces = text.trim().length();

    for (Map.Entry<String, Integer> entry : ReplacementsMap.getInstance().entrySet()) {
        if (entry != null) {

            emoticon = entry.getKey();
            codepoint = entry.getValue();
            String space = "";

            // Now, there either must be spaces around this smiley or this smiley
            // must be the only text present
            if(emoticon.length() != textLengthWithoutSpaces){
                emoticonWithSpaces = " " + emoticon + " ";
                space = " ";
            }else emoticonWithSpaces = emoticon;

            String unicodeChar = getUnicodeChar(codepoint);

            // This will replace all smileys which have a space after and before them
            text = text.replace(
                    emoticonWithSpaces,
                    space + unicodeChar + space        // This will add back the replaced spaces
            );

            // If there's a smiley at the start
            if(text.startsWith(emoticon + " "))
                text = unicodeChar + text.substring(emoticon.length(), text.length());

            // And at the end
            if(text.endsWith(" " + emoticon))
                text = text.substring(0, text.length() - emoticon.length()) + unicodeChar;

        }
    }

    return text;
}
```

It works perfectly in all the 3 cases (spaces around the smiley, smiley at the start, at the end and after a line break) and takes 0-1 ms at most for normal situations.

**Comment by ocram** [comment]
It's important _how_ you measure -- and it seems the way you did it was not correct. Either use a profiler or make sure to use `System.nanoTime()`, measure only the method execution itself, keep in mind that the results are nanoseconds, do lots of iterations and take the average, try to prevent the virtual machine from making certain optimizations, etc.

While it's obvious that your code is faster (it does only plain string replacements), what you did is a micro-optimization. Time spent worrying about those microseconds is lost time. The benefits are negligible.

In our tests, this library needed **1.488556ms** per operation while your code needed **0.116745ms** per operation.

Thus, assuming there was no mistake in the test code, you probably shouldn't care. Unless you're bulding high-performance applications that must save single milliseconds ;)

But in the end, it's up to you which implementation you prefer, of course :)

**Comment by saket** [comment]
While I agreed it depends how you measure and how you use it is important, it can certainly not be termed as micro-optimization when you're developing for mobile where every millisecond counts. I'm using your code (with my modifications) in a list in my app, where I'm supposed to perform any operation within 16ms or visible stutters will start appearing. 

And the list stuttered a lot when the regex pattern was used. Maybe it's not to be used everywhere :)

**Comment by ocram** [comment]
Well, you're right, it's not to be used everywhere :)

If you don't actually measure the performance but add the library to your app and it's slowing down, that is significant in any case. So your optimized solution might be a better fit here.

Most often, this library will be used on user input, right? And it just makes sense to apply the replacements immediately and only _then_ save the user-submitted text to a database, etc. So in that case, you would call this library only _once_ per user and message that is written. The overhead will be super small.

But if you have a list containing _hundreds_ of longer texts, applying the replacements every time a user _views_ the list will definitely be too much overhead. You're right. For that purpose, your solution is better optimized while it does not catch all the emoticons that this library does by default.

Again, however, in a list (adapter) you may call the library only when `getView(...)` etc. is called, i.e. you don't need to apply the replacements to _every_ message, regardless of whether it will actually be visible or not.
